apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alloy-grafana-credentials
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: alloy-grafana-credentials
    creationPolicy: Owner
  data:
    - secretKey: grafana-api-token
      remoteRef:
        key: dev/grafana-cloud/api-token
        property: api_token