apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-db          # → SA "keycloak-db", secret "keycloak-db-app", svc "keycloak-db-rw"
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  instances: 1
  storage:
    storageClass: aws-ebs-gp3
    size: 10Gi
  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak
#   serviceAccountTemplate:
#     metadata:
#       annotations:
#         eks.amazonaws.com/role-arn: 'arn:aws:iam::542776678091:role/cnpg-backup-irsa'
#   backup:
#     barmanObjectStore:
#       destinationPath: 's3://dev-keycloak-cnpg-backups-542776678091-ap-southeast-1-an/'
#       s3Credentials:
#         inheritFromIAMRole: true
#     retentionPolicy: "7d"
# ---
# apiVersion: postgresql.cnpg.io/v1
# kind: ScheduledBackup
# metadata:
#   name: keycloak-db-daily
#   namespace: keycloak
#   annotations:
#     argocd.argoproj.io/sync-wave: "2"
# spec:
#   schedule: "0 0 3 * * *"
#   backupOwnerReference: self
#   cluster:
#     name: "keycloak-db"