apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  project: beginner349
  source:
    repoURL: 'https://charts.external-secrets.io'
    chart: external-secrets
    targetRevision: 2.5.0
    helm:
      valuesObject:
        # for the available values, refer to https://artifacthub.io/packages/helm/external-secrets-operator/external-secrets
        serviceAccount:
          name: external-secrets-sa
          annotations:
            eks.amazonaws.com/role-arn: 'arn:aws:iam::542776678091:role/eso-irsa'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
