apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secret-resources
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  project: beginner349
  source:
    repoURL: 'https://github.com/beginner349/k8s-manifests.git'
    targetRevision: main
    path: secrets
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
