apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: beginner349-dev
  name: deployment-beginner349
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: beginner349-app
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: beginner349-app
    spec:
      serviceAccountName: beginner349-sa
      containers:
        - image: spring-boot-app
          imagePullPolicy: Always
          name: beginner349-app
          ports:
            - containerPort: 8080
          env:
            - name: JWT_ISSUER_URI
              value: https://auth.beginner349.com/realms/myrealm
            - name: OTLP_METRICS_ENDPOINT
              value: http://grafana-alloy.monitoring.svc.cluster.local:4318/v1/metrics
            - name: OTLP_TRACES_ENDPOINT
              value: http://grafana-alloy.monitoring.svc.cluster.local:4318/v1/traces
            - name: OTLP_LOGS_ENDPOINT
              value: http://grafana-alloy.monitoring.svc.cluster.local:4318/v1/logs
            - name: AWS_REGION
              value: ap-southeast-1