apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- 01-namespace.yaml
- 07-serviceaccount.yaml
- 02-deployment.yaml
- 03-service.yaml
- 04-ingressclassparams.yaml
- 05-ingressclass.yaml
- 06-ingress.yaml

images:
- name: spring-boot-app
  newName: 542776678091.dkr.ecr.ap-southeast-1.amazonaws.com/beginner349-app
  newTag: 55a6362f18ef451a0282ab8e9aca2fd423eb5ab7
