name: Deploy to EKS

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  deploy:  
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout Code
      - uses: actions/checkout@v6

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.35.0'

      - name: Update Kubeconfig
        run: |
          aws eks update-kubeconfig --region ${{ vars.AWS_DEFAULT_REGION }} --name my-eks-cluster

      - name: Deploy with Kustomize
        run: |
            cd base
            kustomize edit set image spring-boot-app=${{ vars.AWS_ECR }}/beginner349-app:${{ vars.IMAGE_TAG }}
            kustomize build | kubectl apply -k .